import type { AgentSnapshot } from "@marionette/shared";

export const DEMO_AGENTS: AgentSnapshot[] = [
  {
    agent_id: "demo-agent-1",
    agent_name: "Aria",
    status: "working",
    current_task: "Feature: Add OAuth2 login flow with Google & GitHub providers",
    last_activity: new Date(Date.now() - 2 * 60 * 1000).toISOString(),
    terminal: "VS Code",
    cwd: "/Users/alex/projects/webapp",
    total_runs: 24,
    total_tasks: 87,
    total_errors: 3,
    total_tokens: 1_420_800,
    total_duration_ms: 14_400_000,
    session_start: new Date(Date.now() - 2.5 * 60 * 60 * 1000).toISOString(),
    session_runs: 6,
    session_errors: 0,
    session_tokens: 183_500,
    status_since: new Date(Date.now() - 8 * 60 * 1000).toISOString(),
    metadata: {
      custom_name: "Aria",
      labels: ["auth", "backend"],
      token_budget: 500_000,
    },
  },
  {
    agent_id: "demo-agent-2",
    agent_name: "Titan",
    status: "working",
    current_task: "Bug Investigation: N+1 query causing dashboard to load in 8s",
    last_activity: new Date(Date.now() - 45 * 1000).toISOString(),
    terminal: "Windows Terminal",
    cwd: "C:/Projects/api-service",
    total_runs: 51,
    total_tasks: 210,
    total_errors: 12,
    total_tokens: 3_890_000,
    total_duration_ms: 48_600_000,
    session_start: new Date(Date.now() - 1.2 * 60 * 60 * 1000).toISOString(),
    session_runs: 4,
    session_errors: 1,
    session_tokens: 94_200,
    status_since: new Date(Date.now() - 3 * 60 * 1000).toISOString(),
    metadata: {
      custom_name: "Titan",
      labels: ["perf", "database"],
      jira_tickets: ["PROJ-441"],
    },
  },
  {
    agent_id: "demo-agent-3",
    agent_name: "Echo",
    status: "awaiting_input",
    current_task: "Refactor: Migrate class components to hooks (12 files remaining)",
    last_activity: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    terminal: "iTerm2",
    cwd: "/home/sam/frontend",
    total_runs: 18,
    total_tasks: 63,
    total_errors: 2,
    total_tokens: 980_400,
    total_duration_ms: 9_720_000,
    session_start: new Date(Date.now() - 55 * 60 * 1000).toISOString(),
    session_runs: 3,
    session_errors: 0,
    session_tokens: 61_700,
    status_since: new Date(Date.now() - 4 * 60 * 1000).toISOString(),
    metadata: {
      custom_name: "Echo",
      labels: ["frontend", "refactor"],
      notes: "Waiting for confirmation before deleting legacy HOC wrappers",
    },
  },
  {
    agent_id: "demo-agent-4",
    agent_name: "Nova",
    status: "blocked",
    current_task: "Research: Understanding the codebase payment module",
    last_activity: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
    terminal: "Warp",
    cwd: "/workspace/payments",
    total_runs: 9,
    total_tasks: 31,
    total_errors: 5,
    total_tokens: 540_100,
    total_duration_ms: 5_400_000,
    session_start: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    session_runs: 2,
    session_errors: 2,
    session_tokens: 38_900,
    status_since: new Date(Date.now() - 11 * 60 * 1000).toISOString(),
    metadata: {
      custom_name: "Nova",
      labels: ["payments", "research"],
      jira_tickets: ["PROJ-388", "PROJ-392"],
    },
  },
  {
    agent_id: "demo-agent-5",
    agent_name: "Zion",
    status: "idle",
    current_task: undefined,
    last_activity: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    terminal: "Ghostty",
    cwd: "/Users/jordan/mobile-app",
    total_runs: 35,
    total_tasks: 140,
    total_errors: 4,
    total_tokens: 2_100_000,
    total_duration_ms: 27_000_000,
    session_start: new Date(Date.now() - 4 * 60 * 60 * 1000).toISOString(),
    session_runs: 8,
    session_errors: 0,
    session_tokens: 241_300,
    status_since: new Date(Date.now() - 28 * 60 * 1000).toISOString(),
    metadata: {
      custom_name: "Zion",
      labels: ["mobile", "ios"],
    },
  },
  {
    agent_id: "demo-agent-6",
    agent_name: "Rex",
    status: "error",
    current_task: "Deploy: Run production migration scripts",
    last_activity: new Date(Date.now() - 52 * 60 * 1000).toISOString(),
    terminal: "VS Code",
    cwd: "/srv/deploy",
    total_runs: 14,
    total_tasks: 55,
    total_errors: 18,
    total_tokens: 720_500,
    total_duration_ms: 7_200_000,
    session_start: new Date(Date.now() - 5 * 60 * 60 * 1000).toISOString(),
    session_runs: 3,
    session_errors: 4,
    session_tokens: 52_100,
    status_since: new Date(Date.now() - 52 * 60 * 1000).toISOString(),
    metadata: {
      custom_name: "Rex",
      labels: ["devops", "deploy"],
      jira_tickets: ["OPS-77"],
    },
  },
];
