import type { AgentSession } from "../../services/calendar.service";

const now = Date.now();

function daysAgo(days: number, hours: number, minutes = 0): Date {
  const d = new Date(now);
  d.setDate(d.getDate() - days);
  d.setHours(hours, minutes, 0, 0);
  return d;
}

export const DEMO_CALENDAR_SESSIONS: AgentSession[] = [
  // ── Aria (demo-agent-1) — OAuth2 feature across the week ──
  {
    id: "cal-aria-1",
    agentId: "demo-agent-1",
    agentName: "Aria",
    task: "Feature: OAuth2 planning & package setup",
    startTime: daysAgo(4, 9, 0),
    endTime: daysAgo(4, 11, 30),
    status: "idle",
    tokens: 48_200,
    runs: 2,
    terminal: "VS Code",
    cwd: "/Users/alex/projects/webapp",
  },
  {
    id: "cal-aria-2",
    agentId: "demo-agent-1",
    agentName: "Aria",
    task: "Feature: Passport strategy files & Express router wiring",
    startTime: daysAgo(3, 10, 0),
    endTime: daysAgo(3, 13, 15),
    status: "idle",
    tokens: 72_400,
    runs: 3,
    terminal: "VS Code",
    cwd: "/Users/alex/projects/webapp",
  },
  {
    id: "cal-aria-3",
    agentId: "demo-agent-1",
    agentName: "Aria",
    task: "Feature: Callback URLs via env vars + dev defaults",
    startTime: daysAgo(2, 9, 30),
    endTime: daysAgo(2, 12, 0),
    status: "idle",
    tokens: 61_100,
    runs: 2,
    terminal: "VS Code",
    cwd: "/Users/alex/projects/webapp",
  },
  {
    id: "cal-aria-4",
    agentId: "demo-agent-1",
    agentName: "Aria",
    task: "Feature: Session serialization + Redis store",
    startTime: daysAgo(1, 14, 0),
    endTime: daysAgo(1, 16, 45),
    status: "idle",
    tokens: 58_600,
    runs: 2,
    terminal: "VS Code",
    cwd: "/Users/alex/projects/webapp",
  },
  {
    id: "cal-aria-5",
    agentId: "demo-agent-1",
    agentName: "Aria",
    task: "Feature: Add OAuth2 login flow with Google & GitHub providers",
    startTime: new Date(now - 2.5 * 60 * 60 * 1000),
    endTime: new Date(now),
    status: "working",
    tokens: 183_500,
    runs: 6,
    terminal: "VS Code",
    cwd: "/Users/alex/projects/webapp",
  },

  // ── Titan (demo-agent-2) — N+1 perf investigation ──
  {
    id: "cal-titan-1",
    agentId: "demo-agent-2",
    agentName: "Titan",
    task: "Bug Investigation: Dashboard slowness — initial profiling",
    startTime: daysAgo(4, 15, 0),
    endTime: daysAgo(4, 17, 30),
    status: "idle",
    tokens: 31_800,
    runs: 1,
    terminal: "Windows Terminal",
    cwd: "C:/Projects/api-service",
  },
  {
    id: "cal-titan-2",
    agentId: "demo-agent-2",
    agentName: "Titan",
    task: "Bug Investigation: EXPLAIN ANALYZE — sequential scan identified",
    startTime: daysAgo(3, 9, 0),
    endTime: daysAgo(3, 11, 0),
    status: "idle",
    tokens: 44_900,
    runs: 2,
    terminal: "Windows Terminal",
    cwd: "C:/Projects/api-service",
  },
  {
    id: "cal-titan-3",
    agentId: "demo-agent-2",
    agentName: "Titan",
    task: "Bug Investigation: Composite index + query rewrite + benchmarks",
    startTime: daysAgo(2, 10, 30),
    endTime: daysAgo(2, 13, 0),
    status: "idle",
    tokens: 52_100,
    runs: 2,
    terminal: "Windows Terminal",
    cwd: "C:/Projects/api-service",
  },
  {
    id: "cal-titan-4",
    agentId: "demo-agent-2",
    agentName: "Titan",
    task: "Bug Investigation: N+1 query causing dashboard to load in 8s",
    startTime: new Date(now - 1.2 * 60 * 60 * 1000),
    endTime: new Date(now),
    status: "working",
    tokens: 94_200,
    runs: 4,
    terminal: "Windows Terminal",
    cwd: "C:/Projects/api-service",
  },

  // ── Echo (demo-agent-3) — class → hooks refactor ──
  {
    id: "cal-echo-1",
    agentId: "demo-agent-3",
    agentName: "Echo",
    task: "Refactor: Planning class → hooks migration (12 files)",
    startTime: daysAgo(3, 14, 0),
    endTime: daysAgo(3, 16, 0),
    status: "idle",
    tokens: 22_300,
    runs: 1,
    terminal: "iTerm2",
    cwd: "/home/sam/frontend",
  },
  {
    id: "cal-echo-2",
    agentId: "demo-agent-3",
    agentName: "Echo",
    task: "Refactor: First 4 components converted to hooks",
    startTime: daysAgo(2, 9, 0),
    endTime: daysAgo(2, 12, 30),
    status: "idle",
    tokens: 38_700,
    runs: 2,
    terminal: "iTerm2",
    cwd: "/home/sam/frontend",
  },
  {
    id: "cal-echo-3",
    agentId: "demo-agent-3",
    agentName: "Echo",
    task: "Refactor: Components 5–8 done, getSnapshotBeforeUpdate wrappers",
    startTime: daysAgo(1, 10, 0),
    endTime: daysAgo(1, 13, 0),
    status: "idle",
    tokens: 41_200,
    runs: 2,
    terminal: "iTerm2",
    cwd: "/home/sam/frontend",
  },
  {
    id: "cal-echo-4",
    agentId: "demo-agent-3",
    agentName: "Echo",
    task: "Refactor: Migrate class components to hooks (12 files remaining)",
    startTime: new Date(now - 55 * 60 * 1000),
    endTime: new Date(now - 4 * 60 * 1000),
    status: "awaiting_input",
    tokens: 61_700,
    runs: 3,
    terminal: "iTerm2",
    cwd: "/home/sam/frontend",
  },

  // ── Nova (demo-agent-4) — payment module research ──
  {
    id: "cal-nova-1",
    agentId: "demo-agent-4",
    agentName: "Nova",
    task: "Research: Reading payment module — Stripe Checkout v2 audit",
    startTime: daysAgo(2, 16, 0),
    endTime: daysAgo(2, 17, 30),
    status: "idle",
    tokens: 18_400,
    runs: 1,
    terminal: "Warp",
    cwd: "/workspace/payments",
  },
  {
    id: "cal-nova-2",
    agentId: "demo-agent-4",
    agentName: "Nova",
    task: "Research: Dependency map — blocked on @internal/vault",
    startTime: daysAgo(1, 13, 0),
    endTime: daysAgo(1, 16, 0),
    status: "idle",
    tokens: 29_600,
    runs: 1,
    terminal: "Warp",
    cwd: "/workspace/payments",
  },
  {
    id: "cal-nova-3",
    agentId: "demo-agent-4",
    agentName: "Nova",
    task: "Research: Understanding the codebase payment module",
    startTime: new Date(now - 3 * 60 * 60 * 1000),
    endTime: new Date(now - 11 * 60 * 1000),
    status: "blocked",
    tokens: 38_900,
    runs: 2,
    terminal: "Warp",
    cwd: "/workspace/payments",
  },

  // ── Zion (demo-agent-5) — iOS push notifications ──
  {
    id: "cal-zion-1",
    agentId: "demo-agent-5",
    agentName: "Zion",
    task: "Feature: iOS push notification design & APNs planning",
    startTime: daysAgo(4, 10, 0),
    endTime: daysAgo(4, 14, 0),
    status: "idle",
    tokens: 54_300,
    runs: 3,
    terminal: "Ghostty",
    cwd: "/Users/jordan/mobile-app",
  },
  {
    id: "cal-zion-2",
    agentId: "demo-agent-5",
    agentName: "Zion",
    task: "Feature: APNs integration via @parse/node-apn + retry logic",
    startTime: daysAgo(3, 9, 0),
    endTime: daysAgo(3, 12, 30),
    status: "idle",
    tokens: 78_200,
    runs: 4,
    terminal: "Ghostty",
    cwd: "/Users/jordan/mobile-app",
  },
  {
    id: "cal-zion-3",
    agentId: "demo-agent-5",
    agentName: "Zion",
    task: "Feature: Full test suite run — PR #214 opened",
    startTime: daysAgo(2, 13, 0),
    endTime: daysAgo(2, 15, 30),
    status: "idle",
    tokens: 62_400,
    runs: 3,
    terminal: "Ghostty",
    cwd: "/Users/jordan/mobile-app",
  },
  {
    id: "cal-zion-4",
    agentId: "demo-agent-5",
    agentName: "Zion",
    task: "Deploy: Push notification feature review & addressing feedback",
    startTime: new Date(now - 4 * 60 * 60 * 1000),
    endTime: new Date(now - 28 * 60 * 1000),
    status: "idle",
    tokens: 241_300,
    runs: 8,
    terminal: "Ghostty",
    cwd: "/Users/jordan/mobile-app",
  },

  // ── Rex (demo-agent-6) — production migration ──
  {
    id: "cal-rex-1",
    agentId: "demo-agent-6",
    agentName: "Rex",
    task: "Deploy: Migration script prep & staging dry-run",
    startTime: daysAgo(2, 11, 0),
    endTime: daysAgo(2, 12, 30),
    status: "idle",
    tokens: 19_800,
    runs: 1,
    terminal: "VS Code",
    cwd: "/srv/deploy",
  },
  {
    id: "cal-rex-2",
    agentId: "demo-agent-6",
    agentName: "Rex",
    task: "Deploy: Staging migration test — collation mismatch found",
    startTime: daysAgo(1, 11, 0),
    endTime: daysAgo(1, 14, 0),
    status: "idle",
    tokens: 33_700,
    runs: 2,
    terminal: "VS Code",
    cwd: "/srv/deploy",
  },
  {
    id: "cal-rex-3",
    agentId: "demo-agent-6",
    agentName: "Rex",
    task: "Deploy: Run production migration scripts",
    startTime: new Date(now - 5 * 60 * 60 * 1000),
    endTime: new Date(now - 52 * 60 * 1000),
    status: "error",
    tokens: 52_100,
    runs: 3,
    terminal: "VS Code",
    cwd: "/srv/deploy",
  },
];
